insert into category_three.question_bank (id, prompt, theme, answers, sort_order, version)
values
('classic-41','Name a kind of care that often goes unnoticed.','Care, Family & Everyday Support',ARRAY['Listening','Planning','Cleaning','Reminding']::text[],41,'classic'),
('classic-42','What makes caregiving hardest?','Care, Family & Everyday Support',ARRAY['Not enough time','Not enough money','Not enough help','Not enough recognition']::text[],42,'classic'),
('classic-43','What makes support inside a family feel fair?','Care, Family & Everyday Support',ARRAY['Shared tasks','Shared decisions','Shared time','Shared responsibility']::text[],43,'classic'),
('classic-44','What resource matters most when caring for someone?','Care, Family & Everyday Support',ARRAY['Time','Patience','Money','Community']::text[],44,'classic'),
('classic-45','What does society rely on heavily but often undervalue?','Care, Family & Everyday Support',ARRAY['Child care','Elder care','Emotional support','Household work']::text[],45,'classic'),
('classic-46','What is the strongest form of everyday care?','Care, Family & Everyday Support',ARRAY['Showing up','Checking in','Helping practically','Making time']::text[],46,'classic'),
('classic-47','What makes caring for a family feel more like a choice than an obligation?','Care, Family & Everyday Support',ARRAY['Support','Resources','Flexibility','Respect']::text[],47,'classic'),
('classic-48','What should communities share more often?','Care, Family & Everyday Support',ARRAY['Child care','Meals','Transportation','Useful information']::text[],48,'classic'),
('classic-49','What grows when all care is pushed onto individuals or families?','Care, Family & Everyday Support',ARRAY['Exhaustion','Isolation','Money pressure','Unequal roles']::text[],49,'classic'),
('classic-50','What support helps new parents or caregivers most?','Care, Family & Everyday Support',ARRAY['Paid time off','Affordable care','Nearby help','Flexible schedules']::text[],50,'classic'),
('classic-51','What does a strong family depend on most?','Care, Family & Everyday Support',ARRAY['Care','Trust','Responsibility','Presence']::text[],51,'classic'),
('classic-52','What makes a caring relationship feel less transactional?','Care, Family & Everyday Support',ARRAY['Reciprocity','Affection','Patience','Reliability']::text[],52,'classic'),
('classic-53','What is hardest for money to replace in caring for someone?','Care, Family & Everyday Support',ARRAY['Attention','Trust','Time','Understanding']::text[],53,'classic'),
('classic-54','Why can asking for help feel difficult?','Care, Family & Everyday Support',ARRAY['Pride','Fear of burdening others','Lack of trust','Habit of doing everything alone']::text[],54,'classic'),
('classic-55','When can care turn into a power imbalance?','Care, Family & Everyday Support',ARRAY['One person decides everything','One person controls the money','One person has all the information','One person does all the work']::text[],55,'classic'),
('classic-56','How could society recognize care work better?','Care, Family & Everyday Support',ARRAY['Better pay','More time off','Stronger public services','More shared responsibility']::text[],56,'classic'),
('classic-57','What makes home feel restorative?','Care, Family & Everyday Support',ARRAY['Privacy','Safety','Calm','Cooperation']::text[],57,'classic'),
('classic-58','What does caring for others teach most strongly?','Care, Family & Everyday Support',ARRAY['Patience','Interdependence','Attention','Responsibility']::text[],58,'classic'),
('classic-59','Which kind of care is hardest to measure?','Care, Family & Everyday Support',ARRAY['Emotional care','Preventive care','Background planning','Companionship']::text[],59,'classic'),
('classic-60','When does community care feel most visible?','Care, Family & Everyday Support',ARRAY['During illness','During a crisis','During childcare','During everyday routines']::text[],60,'classic'),
('classic-61','What shapes a person''s identity most over time?','Identity, Roles & Social Expectations',ARRAY['Relationships','Work or school','Culture','Personal choices']::text[],61,'classic'),
('classic-62','When does a social role feel imposed rather than chosen?','Identity, Roles & Social Expectations',ARRAY['There is no real alternative','Refusal brings punishment','Judgment is constant','Dependence makes leaving hard']::text[],62,'classic'),
('classic-63','What most often changes how people see themselves?','Identity, Roles & Social Expectations',ARRAY['New relationships','New responsibilities','New ideas','New environments']::text[],63,'classic'),
('classic-64','When is a social label most useful?','Identity, Roles & Social Expectations',ARRAY['It builds solidarity','It explains an experience','It gives people language','It creates visibility']::text[],64,'classic'),
('classic-65','When does a label become limiting?','Identity, Roles & Social Expectations',ARRAY['It fixes expectations','It hides differences','It replaces curiosity','It becomes a stereotype']::text[],65,'classic'),
('classic-66','What helps people redefine who they are?','Identity, Roles & Social Expectations',ARRAY['Freedom','Community','Resources','Time']::text[],66,'classic'),
('classic-67','What creates the biggest gap between a person and the role expected of them?','Identity, Roles & Social Expectations',ARRAY['Expected behavior','Expected duties','Expected appearance','Expected attitude']::text[],67,'classic'),
('classic-68','Where do social norms feel strongest?','Identity, Roles & Social Expectations',ARRAY['Family','School','Workplace','Media']::text[],68,'classic'),
('classic-69','What makes a shared identity useful for collective action?','Identity, Roles & Social Expectations',ARRAY['A common need','A common harm','A common goal','Mutual support']::text[],69,'classic'),
('classic-70','What keeps identity from becoming fixed?','Identity, Roles & Social Expectations',ARRAY['Curiosity','Choice','Dialogue','Changing circumstances']::text[],70,'classic'),
('classic-71','What shapes behavior more strongly than people like to admit?','Identity, Roles & Social Expectations',ARRAY['Rewards','Punishments','Habits','The need to belong']::text[],71,'classic'),
('classic-72','What most often makes someone resist an assigned role?','Identity, Roles & Social Expectations',ARRAY['It feels unfair','It does not fit them','It feels restrictive','It reduces dignity']::text[],72,'classic'),
('classic-73','What is hardest about rejecting social expectations?','Identity, Roles & Social Expectations',ARRAY['Financial cost','Social conflict','Uncertainty','Loneliness']::text[],73,'classic'),
('classic-74','When does identity feel most authentic?','Identity, Roles & Social Expectations',ARRAY['When it is chosen','When it is supported','When it is lived consistently','When it can still change']::text[],74,'classic'),
('classic-75','How do people usually learn social norms?','Identity, Roles & Social Expectations',ARRAY['By observing others','By being corrected','By being rewarded','By repetition']::text[],75,'classic'),
('classic-76','What can a broad social category easily hide?','Identity, Roles & Social Expectations',ARRAY['Class differences','Cultural differences','Personal history','Power differences']::text[],76,'classic'),
('classic-77','What is most important for solidarity across differences?','Identity, Roles & Social Expectations',ARRAY['Listening','Shared goals','Mutual respect','Practical support']::text[],77,'classic'),
('classic-78','What changes the meaning of a social role from one generation to the next?','Identity, Roles & Social Expectations',ARRAY['Laws','Work patterns','Social movements','Technology']::text[],78,'classic'),
('classic-79','What is a powerful way to challenge a stereotype?','Identity, Roles & Social Expectations',ARRAY['Live differently','Speak openly','Organize together','Change institutions']::text[],79,'classic'),
('classic-80','What creates the biggest tension between individual identity and group identity?','Identity, Roles & Social Expectations',ARRAY['Uniqueness','Belonging','Representation','Responsibility']::text[],80,'classic');
