insert into category_three.question_bank (id, prompt, theme, answers, sort_order, version)
values
('classic-1','What most gives a person a sense of ownership over their own body?','Body & Autonomy',ARRAY['Being able to say no','Choosing their own care','Choosing their own pace','Choosing how they present themselves']::text[],1,'classic'),
('classic-2','Name an everyday situation that can make someone feel less in control of their body.','Body & Autonomy',ARRAY['A rigid schedule','Too little rest','Constant monitoring','Pressure to stay productive']::text[],2,'classic'),
('classic-3','What makes self-determination feel most real?','Body & Autonomy',ARRAY['Freedom to refuse','Freedom to change your mind','Freedom to set boundaries','Freedom to ask for support']::text[],3,'classic'),
('classic-4','Name a body signal people often ignore when life gets too busy.','Body & Autonomy',ARRAY['Fatigue','Hunger','Tension','Need for movement']::text[],4,'classic'),
('classic-5','What can make a personal bodily choice feel less free?','Body & Autonomy',ARRAY['Money pressure','Social pressure','Work pressure','Expert authority']::text[],5,'classic'),
('classic-6','Which personal boundary can be hardest to defend?','Body & Autonomy',ARRAY['Your time','Your personal space','Your privacy','Your need for rest']::text[],6,'classic'),
('classic-7','Name a sign that daily life respects human limits.','Body & Autonomy',ARRAY['Enough sleep','Flexible time','Quiet breaks','Unhurried care']::text[],7,'classic'),
('classic-8','What makes a person feel that their dignity is being respected?','Body & Autonomy',ARRAY['Being listened to','Being asked for consent','Being given enough time','Being trusted']::text[],8,'classic'),
('classic-9','How might freedom be felt physically?','Body & Autonomy',ARRAY['Relaxed breathing','Steady energy','Less tension','Easier movement']::text[],9,'classic'),
('classic-10','What basic need should come before constant productivity?','Body & Autonomy',ARRAY['Rest','Nourishment','Movement','Connection']::text[],10,'classic'),
('classic-11','Name something that can make a person feel treated like a tool instead of a human.','Body & Autonomy',ARRAY['Output being measured','Discomfort being ignored','Breaks being timed','Appearance being judged']::text[],11,'classic'),
('classic-12','What can help someone feel they have reclaimed part of their day?','Body & Autonomy',ARRAY['Choosing their pace','Taking real rest','Moving freely','Disconnecting for a while']::text[],12,'classic'),
('classic-13','What most supports bodily autonomy in everyday life?','Body & Autonomy',ARRAY['Good information','Enough time','Enough resources','Supportive people']::text[],13,'classic'),
('classic-14','Why can a personal choice also be a social issue?','Body & Autonomy',ARRAY['Options depend on cost','Family duties shape options','Work rules shape options','Culture shapes expectations']::text[],14,'classic'),
('classic-15','What is a strong sign that an institution respects bodily autonomy?','Body & Autonomy',ARRAY['Clear consent','Accessible choices','Privacy','A real right to refuse']::text[],15,'classic'),
('classic-16','What kind of knowledge about the body do people tend to trust most?','Body & Autonomy',ARRAY['Lived experience','Repeated body signals','Personal limits','Informed professional advice']::text[],16,'classic'),
('classic-17','How does the body commonly push back against overwork?','Body & Autonomy',ARRAY['Exhaustion','Loss of focus','Irritability','Need for sleep']::text[],17,'classic'),
('classic-18','Name a small freedom people may underestimate.','Body & Autonomy',ARRAY['Choosing when to rest','Choosing how to move','Choosing what to wear','Choosing when to be alone']::text[],18,'classic'),
('classic-19','What can quietly reduce a person''s sense of autonomy?','Body & Autonomy',ARRAY['Rigid scheduling','Constant ranking','Constant tracking','Constant comparison']::text[],19,'classic'),
('classic-20','What best describes a healthy relationship with your own body?','Body & Autonomy',ARRAY['Listening','Patience','Curiosity','Compassion']::text[],20,'classic'),
('classic-21','What makes work feel more human?','Work, Time & Productivity',ARRAY['Control over pace','Meaningful tasks','Enough time','Supportive people']::text[],21,'classic'),
('classic-22','What makes work start to feel mechanical?','Work, Time & Productivity',ARRAY['Repeated tasks','Constant timers','No real decisions','Nonstop monitoring']::text[],22,'classic'),
('classic-23','What is the hardest part of being overworked?','Work, Time & Productivity',ARRAY['Losing personal time','Losing connection with others','Constant fatigue','No mental space']::text[],23,'classic'),
('classic-24','What is a better sign of good work than simply doing more?','Work, Time & Productivity',ARRAY['Quality','Sustainability','Usefulness','Learning']::text[],24,'classic'),
('classic-25','Besides money, what do people most need from work?','Work, Time & Productivity',ARRAY['Respect','Purpose','Control','Belonging']::text[],25,'classic'),
('classic-26','How does workplace pressure most often show up?','Work, Time & Productivity',ARRAY['Pressure to go faster','Pressure to be always available','Pressure to hit targets','Pressure to monitor yourself']::text[],26,'classic'),
('classic-27','What makes a worker feel more free?','Work, Time & Productivity',ARRAY['Choosing how to work','Choosing their pace','Choosing when to pause','Having a real voice']::text[],27,'classic'),
('classic-28','What can drain the life out of a job fastest?','Work, Time & Productivity',ARRAY['Unpredictability','Repetition','Surveillance','Meaningless tasks']::text[],28,'classic'),
('classic-29','Modern life often treats time as what?','Work, Time & Productivity',ARRAY['Money','A schedule','A target','A resource']::text[],29,'classic'),
('classic-30','What kind of break is most restorative during a long day?','Work, Time & Productivity',ARRAY['Quiet time','A little movement','A good conversation','Time outdoors']::text[],30,'classic'),
('classic-31','What makes a job feel worth staying in?','Work, Time & Productivity',ARRAY['Fair pay','Manageable hours','Respect','Autonomy']::text[],31,'classic'),
('classic-32','If automation improves work, what should it reduce first?','Work, Time & Productivity',ARRAY['Repetitive tasks','Dangerous tasks','Administrative tasks','After-hours tasks']::text[],32,'classic'),
('classic-33','What is most at risk when efficiency becomes the main value?','Work, Time & Productivity',ARRAY['People get rushed','Care gets reduced','Creativity gets reduced','Rest disappears']::text[],33,'classic'),
('classic-34','What would make the future of work feel more humane?','Work, Time & Productivity',ARRAY['Shorter workdays','Flexible hours','Shared decisions','Stable security']::text[],34,'classic'),
('classic-35','Name a kind of work that often stays invisible.','Work, Time & Productivity',ARRAY['Planning','Emotional support','Caregiving','Household coordination']::text[],35,'classic'),
('classic-36','What do people often confuse with being busy?','Work, Time & Productivity',ARRAY['Being useful','Being responsible','Being important','Being productive']::text[],36,'classic'),
('classic-37','What can create burnout fastest?','Work, Time & Productivity',ARRAY['No control','No rest','No recognition','No boundaries']::text[],37,'classic'),
('classic-38','What is the clearest sign that a job respects the body?','Work, Time & Productivity',ARRAY['Real breaks','A safe pace','Reasonable hours','Comfortable working conditions']::text[],38,'classic'),
('classic-39','Who does your time feel like it belongs to most on a normal weekday?','Work, Time & Productivity',ARRAY['Yourself','Your family','Your school or workplace','Your community']::text[],39,'classic'),
('classic-40','What activity best helps someone recover after a demanding day?','Work, Time & Productivity',ARRAY['Sleep','A walk','Talking with someone','A creative hobby']::text[],40,'classic');
